---
- name: Ensure pihole container is down
  community.docker.docker_compose_v2:
    project_src: "{{ pihole__deployment_directory }}"
    env_files: "{{ __pihole__container_env_file }}"
    project_name: "{{ pihole__container_name }}"
    remove_orphans: true
    state: absent

- name: Recursively remove pihole directories
  ansible.builtin.file:
    path: "{{ item }}"
    state: absent
  with_items:
    - "{{ pihole__deployment_directory }}"
    - "{{ __pihole__ansible_role_conf_dir }}"
