.DEFAULT_GOAL := up

.PHONY: up
up:
	docker compose --env-file {{ __pihole__container_env_file }} up -d

.PHONY: down
down:
	docker compose --env-file {{ __pihole__container_env_file }} down

.PHONY: cleanup
cleanup: down
	sudo rm -rf etc-pihole
	sudo rm -rf {{ __pihole__ansible_role_conf_dir }}
